### ISSUE TITLE
I have 2 questions

### ISSUE THREAD

**Issue by sevydev** [zero-to-mastery/travel-guide#529]
1. I forked the original repo,it's up to date but I can't seem to see the final version of the website locally as it's shown here on github link. why?
2. e.g. I'd like to add turkey on the list of Europe with flag and everything. In which index file am I supposed to do that? The files are a little bit complicated and I don't know where to start. 
Thanks

**Comment by mirhatx** [comment]
1.  if you forked, go your profile and copy  your forked repository's link then clone it because you don't have permission for the main repository if you don't know how to clone checkout the Git + Github section on the course, but simply:

open cmd or other terminal apps on your computer and:
git clone yourforkrepolink
cd travel-guide
npm run install
npm run start
enter [http://localhost:3000] in your browser

2. Turkey is already exists But the api sends flags to website that's why the flag is in the Asia Card
i'm from Turkey btw. Selamlar
